<#
.SYNOPSIS
  AI-only preflight guard to prevent wrong-repo edits.

.DESCRIPTION
  Requires SELENITE_AI_SESSION=1, runs workspace-guard, prints workspace state,
  and optionally enforces an expected role (dev/prod). Sets a session-scoped
  SELENITE_GUARD_PASSED=1 flag on success.
#>
[CmdletBinding()]
param(
  [ValidateSet('dev', 'prod', 'any')]
  [string]$ExpectedRole = 'any'
)

$ErrorActionPreference = 'Stop'

if ($env:SELENITE_AI_SESSION -ne '1') {
  throw "[ai-preflight] SELENITE_AI_SESSION=1 is required for AI sessions."
}
$env:SELENITE_AI_ENFORCE = '1'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptDir
$roleFile = Join-Path $repoRoot ".workspace-role"
$stateFile = Join-Path $repoRoot ".workspace-state.json"
$agentsPath = Join-Path $repoRoot "AGENTS.md"
$charterPath = Join-Path $repoRoot "docs/AI_COLLAB_CHARTER.md"

if (-not (Test-Path $roleFile)) {
  throw "[ai-preflight] Missing .workspace-role in $repoRoot."
}

$missingFiles = @()
if (-not (Test-Path $agentsPath)) { $missingFiles += $agentsPath }
if (-not (Test-Path $charterPath)) { $missingFiles += $charterPath }
if ($missingFiles.Count -gt 0) {
  throw "[ai-preflight] Missing required files: $($missingFiles -join ', ')"
}

$role = (Get-Content -Path $roleFile -ErrorAction Stop | Select-Object -First 1).Trim().ToLowerInvariant()
if ($ExpectedRole -ne 'any' -and $role -ne $ExpectedRole) {
  throw "[ai-preflight] Expected role '$ExpectedRole' but found '$role' in $repoRoot."
}

$state = $null
if (Test-Path $stateFile) {
  try {
    $state = Get-Content -Path $stateFile -Raw | ConvertFrom-Json
  } catch {
    $state = $null
  }
}

$agentsHash = (Get-FileHash -Path $agentsPath -Algorithm SHA256).Hash
$charterHash = (Get-FileHash -Path $charterPath -Algorithm SHA256).Hash
Write-Host "[ai-preflight] AGENTS.md SHA256: $agentsHash" -ForegroundColor Yellow
Write-Host "[ai-preflight] AI_COLLAB_CHARTER.md SHA256: $charterHash" -ForegroundColor Yellow

$guardScript = Join-Path $scriptDir "workspace-guard.ps1"
if (-not (Test-Path $guardScript)) {
  throw "[ai-preflight] Missing workspace-guard.ps1."
}
$env:SELENITE_PREFLIGHT_RUNNING = '1'
& $guardScript
Remove-Item Env:SELENITE_PREFLIGHT_RUNNING -ErrorAction SilentlyContinue

$showStateScript = Join-Path $scriptDir "show-workspace-state.ps1"
if (Test-Path $showStateScript) {
  & $showStateScript
} else {
  Write-Host "[ai-preflight] show-workspace-state.ps1 not found; skipping state display." -ForegroundColor Yellow
}

$sessionDir = Join-Path $repoRoot "docs/memorialization/ai-sessions"
New-Item -ItemType Directory -Force -Path $sessionDir | Out-Null
$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$sessionPath = Join-Path $sessionDir "ai-session-$timestamp.md"
$stateValue = if ($state -and $state.state) { $state.state } else { "unknown" }
$canonicalOwner = if ($state -and $state.canonical_owner) { $state.canonical_owner } else { "unknown" }
$sessionLog = @"
# AI Session Log
Timestamp: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
Repo root: $repoRoot
Workspace role: $role
Workspace state: $stateValue
Canonical owner: $canonicalOwner
AGENTS.md SHA256: $agentsHash
AI_COLLAB_CHARTER.md SHA256: $charterHash
Note: This log is auto-generated by ai-preflight.
"@
Set-Content -Path $sessionPath -Value $sessionLog -Encoding ascii
Write-Host "[ai-preflight] Session log: $sessionPath" -ForegroundColor Yellow

$env:SELENITE_GUARD_PASSED = '1'
Write-Host "[ai-preflight] Guard passed for role '$role' at $repoRoot." -ForegroundColor Green
